### ISSUE TITLE
Not working in GNU Emacs 26.1 and 25.3.1

### ISSUE THREAD

**Issue by alaneuler** [mneilly/Emacs-Persistent-Overlays#1]
I installed the .el file from MELPA, created directory ~/.emacs-persistent-overlays, added following to my ~/.emacs:
```
(load-library "persistent-overlays")
(add-hook 'prog-mode-hook (lambda () (hs-minor-mode 1) (setq hs-allow-nesting t) (persistent-overlays-minor-mode 1)))
```

I've tested it with a test.c file which resides in my home directory with command `C-c @ C-h` to fold my main function; then exit with `C-x C-c`. However, the folding is not persistent after I reopen the test.c file.

I've tested with both GNU Emacs 25.3.1 and 26.1, neither worked.

BTW, the evaluation of `(print persistent-overlays-directory)` in \*scratch\* buffer print
```
"~/.emacs-persistent-overlays"
"~/.emacs-persistent-overlays"
```
Is something wrong with this?

**Comment by mneilly** [comment]
A few questions:

- What program mode are you using? C? C++? Something else?
- Does "povly" show in your mode line?
- Are any files created in ~/.emacs-persistent-overlays?
- Is there any output in your *Messages* buffer related to persistent-overlays?
- Can you try running persistent-overlays-save-overlays or C-c * C-s?

**Comment by mneilly** [comment]
To clarify, when you say you "exit with C-x C-c" you did save the file first, correct? The overlays are only saved when you save your file.

**Comment by alaneuler** [comment]
Hi, mneilly

I find what is wrong here. Before I hide the `main` function, I do the saving of file then hide, then I exit emacs. In this situation, the overlays are not saved.

However, if I do the hiding before the the saving of file, the overlays are saved.

It makes a little difference. Thank you for your help!
And this extension is what I want for a long time! Thank you for your work!

**Comment by mneilly** [comment]
Hey, great. Glad to hear it is working for you. :)
